// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ74UGThSA61N7Rlvwd8UxE3K7V4sqTQM',
    appId: '1:362887834949:web:adf244376e335dd854622c',
    messagingSenderId: '362887834949',
    projectId: 'barber-project-13adf',
    authDomain: 'barber-project-13adf.firebaseapp.com',
    storageBucket: 'barber-project-13adf.firebasestorage.app',
    measurementId: 'G-TLGMFH3KGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQqm9xhXnpox9r_UzCCKTNbil8IESeM1I',
    appId: '1:362887834949:android:60d4b59e497667b854622c',
    messagingSenderId: '362887834949',
    projectId: 'barber-project-13adf',
    storageBucket: 'barber-project-13adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzfv5gxxFmtFWTLywvFrgRaLwgDSbM9oE',
    appId: '1:362887834949:ios:b7660708a22b1d8354622c',
    messagingSenderId: '362887834949',
    projectId: 'barber-project-13adf',
    storageBucket: 'barber-project-13adf.firebasestorage.app',
    iosBundleId: 'com.example.hairguideBarberpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzfv5gxxFmtFWTLywvFrgRaLwgDSbM9oE',
    appId: '1:362887834949:ios:b7660708a22b1d8354622c',
    messagingSenderId: '362887834949',
    projectId: 'barber-project-13adf',
    storageBucket: 'barber-project-13adf.firebasestorage.app',
    iosBundleId: 'com.example.hairguideBarberpedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ74UGThSA61N7Rlvwd8UxE3K7V4sqTQM',
    appId: '1:362887834949:web:764c87f8b5e5054254622c',
    messagingSenderId: '362887834949',
    projectId: 'barber-project-13adf',
    authDomain: 'barber-project-13adf.firebaseapp.com',
    storageBucket: 'barber-project-13adf.firebasestorage.app',
    measurementId: 'G-39NEKFEENS',
  );
}
